version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "3001:80"
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/app
  php:
    build: .
    volumes:
      - ./src:/app
  mysql:
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=asdfasdf
      - MYSQL_USER=tutoring
      - MYSQL_PASSWORD=garnichts
      - MYSQL_DATABASE=tutoring
