version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "3001:80"
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/app
  php:
    image: php:fpm
    volumes:
      - ./src:/app
